# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 500)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.plateNumberInput = QtWidgets.QLineEdit(self.centralwidget)
        self.plateNumberInput.setObjectName("plateNumberInput")
        self.verticalLayout.addWidget(self.plateNumberInput)
        self.areaInput = QtWidgets.QLineEdit(self.centralwidget)
        self.areaInput.setObjectName("areaInput")
        self.verticalLayout.addWidget(self.areaInput)
        self.expiryDateInput = QtWidgets.QDateEdit(self.centralwidget)
        self.expiryDateInput.setObjectName("expiryDateInput")
        self.verticalLayout.addWidget(self.expiryDateInput)
        self.stickerTypeCombo = QtWidgets.QComboBox(self.centralwidget)
        self.stickerTypeCombo.setObjectName("stickerTypeCombo")
        self.stickerTypeCombo.addItem("")
        self.stickerTypeCombo.addItem("")
        self.stickerTypeCombo.addItem("")
        self.verticalLayout.addWidget(self.stickerTypeCombo)
        self.qrCodeLabel = QtWidgets.QLabel(self.centralwidget)
        self.qrCodeLabel.setMinimumSize(QtCore.QSize(150, 150))
        self.qrCodeLabel.setText("")
        self.qrCodeLabel.setObjectName("qrCodeLabel")
        self.verticalLayout.addWidget(self.qrCodeLabel)
        self.generateQRButton = QtWidgets.QPushButton(self.centralwidget)
        self.generateQRButton.setObjectName("generateQRButton")
        self.verticalLayout.addWidget(self.generateQRButton)
        self.printStickerButton = QtWidgets.QPushButton(self.centralwidget)
        self.printStickerButton.setObjectName("printStickerButton")
        self.verticalLayout.addWidget(self.printStickerButton)
        self.saveRecordButton = QtWidgets.QPushButton(self.centralwidget)
        self.saveRecordButton.setObjectName("saveRecordButton")
        self.verticalLayout.addWidget(self.saveRecordButton)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        self.plateNumberInput.setPlaceholderText(_translate("MainWindow", "Enter Plate Number"))
        self.areaInput.setPlaceholderText(_translate("MainWindow", "Enter Area"))
        self.stickerTypeCombo.setItemText(0, _translate("MainWindow", "Standard"))
        self.stickerTypeCombo.setItemText(1, _translate("MainWindow", "Visitor"))
        self.stickerTypeCombo.setItemText(2, _translate("MainWindow", "Contractor"))
        self.generateQRButton.setText(_translate("MainWindow", "Generate QR"))
        self.printStickerButton.setText(_translate("MainWindow", "Print Sticker"))
        self.saveRecordButton.setText(_translate("MainWindow", "Save Record"))
